import cobordism_concordance_topological_manifolds_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace cobordism_concordance_topological_manifolds_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end cobordism_concordance_topological_manifolds_lemma_canonical_lane_mathlib
end HautevilleHouse
